server:
  port: 8761
  
info:
  component: MCB service registry (based on Netflix Eureka)
  
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org.springframework.web: INFO
    com.discovery: DEBUG
    
ribbon:
  ConnectTimeout: 300000
  ReadTimeout: 600000  